const Productdata = [
  {
    id: 1,
    name: "TrustBasket Single Pot ",
    image: "https://m.media-amazon.com/images/I/81OUqN3ns-L._SX679_.jpg",
    Brand: "TrustBasket",
    price: 703,
    rating: "4.5",
    color: "Multicolor",
    qnty: 0,
  },
  {
    id: 2,
    name: "Lenovo IdeaPad ",
    image: "https://m.media-amazon.com/images/I/61Dw5Z8LzJL._AC_UL320_.jpg",
    Brand: "Lenovo",
    price: 35990.0,
    rating: "4.8",
    color: "Platinum Grey",
    qnty: 0,
  },
  {
    id: 3,
    name: "On Ear Headphones ",
    image: "https://m.media-amazon.com/images/I/51dgKyMXmhL._AC_UL320_.jpg",
    Brand: "Macmerise",
    price: 1699,
    rating: "4.5",
    color: "Multicolour",
    qnty: 0,
  },
  {
    id: 4,
    name: "Redmi Smart TV 32 ",
    image: "https://m.media-amazon.com/images/I/71HcZHyEsTL._SX569_.jpg",
    Brand: "Redmi",
    price: 15499.0,
    rating: "4.6",
    color: "Black",
    qnty: 0,
  },
  {
    id: 5,
    name: "T-Shirts ",
    image: "https://m.media-amazon.com/images/I/51RP5CKYdoL._UX679_.jpg",
    Brand: "JUNEBERRY",

    price: 399,
    rating: "5.2",
    color: "Multicolor",
    qnty: 0,
  },
  {
    id: 6,
    name: "boAt Airdopes",
    image: "https://m.media-amazon.com/images/I/71ByNT34bfL._SX450_.jpg",
    Brand: "boAt",
    price: 1299,
    rating: "4.6",
    color: "Black",
    qnty: 0,
  },
  {
    id: 7,
    name: "Wall Clock ",
    image: "https://m.media-amazon.com/images/I/81rbLQ-Q-wL._SY450_.jpg",
    Brand: "OREVA",
    price: 389,
    rating: "4.9",
    color: "Brown",
    qnty: 0,
  },
  {
    id: 8,
    name: "Tower Speaker",
    image: "https://m.media-amazon.com/images/I/91Fi2PcphzL._SY450_.jpg",
    Brand: "OBAGE",
    price: 4299,
    rating: "4.4",
    color: "Brown",
    qnty: 0,
  },
  {
    id: 9,
    name: "Mixer Grinder",
    image: "https://m.media-amazon.com/images/I/51B0MPbLbXL._SX569_.jpg",
    Brand: "Philips",
    price: 3485,
    rating: "4.7",
    color: "Black",
    qnty: 0,
  },
  {
    id: 10,
    name: "Cushion Cover",
    image: "https://m.media-amazon.com/images/I/815-Falps7L._SX450_.jpg",
    Brand: "	BLUE GRASS",
    price: 269,
    rating: "4.5",
    color: "Multicolor",
    qnty: 0,
  },
  {
    id: 11,
    name: "Heel Sandals",
    image: "https://m.media-amazon.com/images/I/91ZuIZ9Bb0L._UY625_.jpg",
    Brand: "BULLFER",
    price: 299,
    rating: "4.8",
    color: "Pink",
    qnty: 0,
  },
  {
    id: 12,
    name: "Glass Coffee Mug ",
    image: "https://m.media-amazon.com/images/I/41yZ8ZmaHPL.jpg",
    Brand: "Simran Handicrafts",
    price: 309,
    rating: "4.6",
    color: "Multicolour",
    qnty: 0,
  },
];

export default Productdata